<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.mesa.org/xml/B2MML-V0600" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="ns0 xs fn" xmlns:msxsl="urn:schemas-microsoft-com:xslt"  extension-element-prefixes="msxsl">

	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes" omit-xml-declaration="yes"/>
	<xsl:template match="/">
		<ProcessMaterialLot  xmlns="http://www.mesa.org/xml/B2MML-V0600" xmlns:ns="http://www.mesa.org/xml/B2MML-V0600" releaseID="B2MML-V0600" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<ApplicationArea>
				<Sender>
					<LogicalID>
						<xsl:value-of select="/*[local-name()='ZWMMBID01']/*[local-name()='IDOC']/*[local-name()='EDI_DC40']/*[local-name()='SNDPOR']" />
					</LogicalID>
					<ReferenceID>
						<xsl:value-of select="/*[local-name()='ZWMMBID01']/*[local-name()='IDOC']/*[local-name()='EDI_DC40']/*[local-name()='DOCNUM']" />
					</ReferenceID>
					<ConfirmationCode>Always</ConfirmationCode>
					<AuthorizationID>normalizedString</AuthorizationID>
				</Sender>
				<Receiver>
					<LogicalID>normalizedString</LogicalID>
					<ComponentID>normalizedString</ComponentID>
					<ID>normalizedString</ID>
				</Receiver>
				<CreationDateTime>
					<xsl:value-of select="concat(substring(/ZWMMBID01/IDOC/EDI_DC40/CREDAT,1,4),'-',substring(/ZWMMBID01/IDOC/EDI_DC40/CREDAT,5,2),'-',substring(/ZWMMBID01/IDOC/EDI_DC40/CREDAT,7,2),'T',substring(/ZWMMBID01/IDOC/EDI_DC40/CRETIM,1,2),':',substring(/ZWMMBID01/IDOC/EDI_DC40/CRETIM,3,2),':',substring(/ZWMMBID01/IDOC/EDI_DC40/CRETIM,5,2),'Z')" />
				</CreationDateTime>
				<BODID>normalizedString</BODID>
			</ApplicationArea>
			<DataArea>
				<Process>
					<ActionCriteria>
						<ActionExpression actionCode="">token</ActionExpression>
						<ChangeStatus>
							<Code>normalizedString</Code>
							<Description>String</Description>
							<EffectiveDateTime>1999-05-31T13:20:00.000-05:00</EffectiveDateTime>
							<ReasonCode>normalizedString</ReasonCode>
							<Reason>normalizedString</Reason>
							<StateChange>
								<FromStateCode>normalizedString</FromStateCode>
								<ToStateCode>normalizedString</ToStateCode>
								<ChangeDateTime>1999-05-31T13:20:00.000-05:00</ChangeDateTime>
								<Description>String</Description>
								<Note>String</Note>
							</StateChange>
						</ChangeStatus>
					</ActionCriteria>
				</Process>
				<xsl:for-each select="/*[local-name()='ZWMMBID01']/*[local-name()='IDOC']/*[local-name()='E1MBXYH']/*[local-name()='E1MBXYI']">
					<MaterialLot>
						<ID>
							<xsl:value-of select="CHARG" />
						</ID>
						<Description>String</Description>
						<Location>
							<EquipmentID>normalizedString</EquipmentID>
							<EquipmentElementLevel>Area</EquipmentElementLevel>
						</Location>
						<HierarchyScope>
							<EquipmentID>
								<xsl:value-of select="WERKS" />
							</EquipmentID>
							<EquipmentElementLevel>WorkCell</EquipmentElementLevel>
						</HierarchyScope>
						<MaterialDefinitionID>
							<xsl:value-of select="MATNR" />
						</MaterialDefinitionID>

						<!-- STATUS VARIABLE -->
						<xsl:variable name="concatenatedStatusValues">
							<xsl:for-each select="//ZE1CLAS">
								<xsl:if test="CHARACT='LOBM_UDCODE'">
									<xsl:value-of select="VALUE_NEUTRAL" />
								</xsl:if>
							</xsl:for-each>
							<xsl:text>|</xsl:text>
							<xsl:value-of select="INSMK"/>
							<xsl:text>|</xsl:text>
							<xsl:value-of select="UMZUS"/>
						</xsl:variable>

						<!-- Use the STATUS VARIABLE -->
						<Status>
							<xsl:value-of select="$concatenatedStatusValues"/>
						</Status>
						
						<MaterialLotProperty>
							<ID>RevaluationDateUtc</ID>
							<Description>String</Description>
							<Value>
								<ValueString>
									<xsl:value-of select="DABRZ" />
								</ValueString>
							</Value>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>SourceLastUpdateTime</ID>
							<Description>String</Description>
							<Value>
								<ValueString>1999-05-31T13:20:00.000-05:00</ValueString>
								<DataType>unsignedShort</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>SourceLastUpdateTime</ID>
								<Description>String</Description>
								<TestDateTime>1999-05-31T13:20:00.000-05:00</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>Text</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>1999-05-31T13:20:00.000-05:00</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>UsageDecisionText</ID>
							<Description>String</Description>
							<Value>
								<ValueString>
									<xsl:choose>
										<xsl:when test="//ZE1CLAS//CHARACT[text()='LOBM_UDCODE']">
											<xsl:for-each select="//ZE1CLAS">
												<xsl:if test="CHARACT='LOBM_UDCODE'">
													<xsl:value-of select="VALUE_NEUTRAL" />
												</xsl:if>
											</xsl:for-each>
										</xsl:when>
										<xsl:otherwise>0</xsl:otherwise>
									</xsl:choose>
								</ValueString>
								<DataType>double</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<TestDateTime>1999-05-31T13:20:00.000-05:00</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>unsignedShort</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>1999-05-31T13:20:00.000-05:00</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>MaterialLotPotency</ID>
							<Description>String</Description>
							<Value>
								<ValueString>
									<xsl:choose>
										<xsl:when test="//ZE1CLAS//CHARACT[text()='POTENCY_2']">
											<xsl:for-each select="//ZE1CLAS">
												<xsl:if test="CHARACT='POTENCY_2'">
													<xsl:value-of select="VALUE_NEUTRAL" />
												</xsl:if>
											</xsl:for-each>
										</xsl:when>
										<xsl:otherwise>0</xsl:otherwise>
									</xsl:choose>
								</ValueString>
								<DataType>double</DataType>
								<UnitOfMeasure>
									<xsl:value-of select="EVERS" />
								</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<TestDateTime>1999-05-31T13:20:00.000-05:00</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>unsignedShort</DataType>
									<UnitOfMeasure>
										<xsl:value-of select="EVERS" />
									</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>1999-05-31T13:20:00.000-05:00</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>SupplierID</ID>
							<Description>String</Description>
							<Value>
								<ValueString></ValueString>
								<DataType>double</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<TestDateTime>1999-05-31T13:20:00.000-05:00</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>unsignedShort</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>1999-05-31T13:20:00.000-05:00</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>SupplierName</ID>
							<Description>String</Description>
							<Value>
								<ValueString></ValueString>
								<DataType>double</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<TestDateTime>1999-05-31T13:20:00.000-05:00</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>unsignedShort</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>1999-05-31T13:20:00.000-05:00</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>SupplierLotID</ID>
							<Description>String</Description>
							<Value>
								<ValueString>
									<xsl:for-each select="/*[local-name()='ZWMMBID01']/*[local-name()='IDOC']/*[local-name()='E1MBXYH']/*[local-name()='E1MBXYI']/*[local-name()='ZE1CLAS']">
										<xsl:if test="CHARACT='VENDOR_BATCH'">
											<xsl:value-of select="VALUE_NEUTRAL" />
										</xsl:if>
									</xsl:for-each>
								</ValueString>
								<DataType>double</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<TestDateTime>1999-05-31T13:20:00.000-05:00</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>unsignedShort</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>1999-05-31T13:20:00.000-05:00</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialLotProperty>
							<ID>ReferencedMaterialLots</ID>
							<Description>String</Description>
							<Value>
								<ValueString></ValueString>
								<DataType>double</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Value>
							<MaterialLotProperty>
								<ID>MaterialLot</ID>
								<Description>String</Description>
								<Value>
									<ValueString></ValueString>
									<DataType>double</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Value>
								<MaterialLotProperty>
									<ID>SourceSystemID</ID>
									<Description>String</Description>
									<Value>
										<ValueString>
											<xsl:value-of select="/*[local-name()='ZWMMBID01']/*[local-name()='IDOC']/*[local-name()='EDI_DC40']/*[local-name()='SNDPOR']" />
										</ValueString>
										<DataType>double</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Value>
									<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
									<TestResult>
										<ID>normalizedString</ID>
										<Description>String</Description>
										<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
										<Result>
											<ValueString>String</ValueString>
											<DataType>unsignedShort</DataType>
											<UnitOfMeasure>normalizedString</UnitOfMeasure>
											<Key>normalizedString</Key>
										</Result>
										<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
									</TestResult>
								</MaterialLotProperty>
								<MaterialLotProperty>
									<ID>PlantID</ID>
									<Description>String</Description>
									<Value>
										<ValueString>
											<xsl:value-of select="WERKS" />
										</ValueString>
										<DataType>double</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Value>
									<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
									<TestResult>
										<ID>normalizedString</ID>
										<Description>String</Description>
										<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
										<Result>
											<ValueString>String</ValueString>
											<DataType>unsignedShort</DataType>
											<UnitOfMeasure>normalizedString</UnitOfMeasure>
											<Key>normalizedString</Key>
										</Result>
										<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
									</TestResult>
								</MaterialLotProperty>
								<MaterialLotProperty>
									<ID>MaterialID</ID>
									<Description>String</Description>
									<Value>
										<ValueString>
											<xsl:value-of select="MATNR" />
										</ValueString>
										<DataType>double</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Value>
									<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
									<TestResult>
										<ID>normalizedString</ID>
										<Description>String</Description>
										<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
										<Result>
											<ValueString>String</ValueString>
											<DataType>unsignedShort</DataType>
											<UnitOfMeasure>normalizedString</UnitOfMeasure>
											<Key>normalizedString</Key>
										</Result>
										<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
									</TestResult>
								</MaterialLotProperty>
								<MaterialLotProperty>
									<ID>MaterialLotID</ID>
									<Description>String</Description>
									<Value>
										<ValueString>
											<xsl:value-of select="CHARG" />
										</ValueString>
										<DataType>double</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Value>
									<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
									<TestResult>
										<ID>normalizedString</ID>
										<Description>String</Description>
										<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
										<Result>
											<ValueString>String</ValueString>
											<DataType>unsignedShort</DataType>
											<UnitOfMeasure>normalizedString</UnitOfMeasure>
											<Key>normalizedString</Key>
										</Result>
										<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
									</TestResult>
								</MaterialLotProperty>
								<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
								<TestResult>
									<ID>normalizedString</ID>
									<Description>String</Description>
									<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
									<Result>
										<ValueString>String</ValueString>
										<DataType>unsignedShort</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Result>
									<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
								</TestResult>
							</MaterialLotProperty>
							<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
							<TestResult>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
								<Result>
									<ValueString>String</ValueString>
									<DataType>unsignedShort</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Result>
								<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
							</TestResult>
						</MaterialLotProperty>
						<MaterialSubLot>
							<ID>normalizedString</ID>
							<Description>String</Description>
							<Location>
								<EquipmentID>normalizedString</EquipmentID>
								<EquipmentElementLevel>WorkUnit</EquipmentElementLevel>
							</Location>
							<HierarchyScope>
								<EquipmentID>normalizedString</EquipmentID>
								<EquipmentElementLevel>Area</EquipmentElementLevel>
							</HierarchyScope>
							<Status>normalizedString</Status>
							<MaterialSublotProperty>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<Value>
									<ValueString>String</ValueString>
									<DataType>long</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Value>
								<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
								<TestResult>
									<ID>normalizedString</ID>
									<Description>String</Description>
									<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
									<Result>
										<ValueString>String</ValueString>
										<DataType>NMTOKENS</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Result>
									<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
								</TestResult>
							</MaterialSublotProperty>
							<StorageLocation>normalizedString</StorageLocation>
							<Quantity>
								<QuantityString>String</QuantityString>
								<DataType>nonNegativeInteger</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Quantity>
							<MaterialLotID>normalizedString</MaterialLotID>
							<AssemblyType>Logical</AssemblyType>
							<AssemblyRelationship>Transient</AssemblyRelationship>
						</MaterialSubLot>
						<StorageLocation>normalizedString</StorageLocation>
						<Quantity>
							<QuantityString>String</QuantityString>
							<DataType>timePeriod</DataType>
							<UnitOfMeasure>normalizedString</UnitOfMeasure>
							<Key>normalizedString</Key>
						</Quantity>
						<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
						<AssemblySubLotID>
							<ID>normalizedString</ID>
							<Description>String</Description>
							<Location>
								<EquipmentID>normalizedString</EquipmentID>
								<EquipmentElementLevel>ProductionLine</EquipmentElementLevel>
							</Location>
							<HierarchyScope>
								<EquipmentID>normalizedString</EquipmentID>
								<EquipmentElementLevel>ProductionLine</EquipmentElementLevel>
							</HierarchyScope>
							<Status>normalizedString</Status>
							<MaterialSublotProperty>
								<ID>normalizedString</ID>
								<Description>String</Description>
								<Value>
									<ValueString>String</ValueString>
									<DataType>Measure</DataType>
									<UnitOfMeasure>normalizedString</UnitOfMeasure>
									<Key>normalizedString</Key>
								</Value>
								<MaterialTestSpecificationID>normalizedString</MaterialTestSpecificationID>
								<TestResult>
									<ID>normalizedString</ID>
									<Description>String</Description>
									<TestDateTime>2001-12-17T09:30:47Z</TestDateTime>
									<Result>
										<ValueString>String</ValueString>
										<DataType>time</DataType>
										<UnitOfMeasure>normalizedString</UnitOfMeasure>
										<Key>normalizedString</Key>
									</Result>
									<ExpirationTime>2001-12-17T09:30:47Z</ExpirationTime>
								</TestResult>
							</MaterialSublotProperty>
							<StorageLocation>normalizedString</StorageLocation>
							<Quantity>
								<QuantityString>String</QuantityString>
								<DataType>byte</DataType>
								<UnitOfMeasure>normalizedString</UnitOfMeasure>
								<Key>normalizedString</Key>
							</Quantity>
							<MaterialLotID>normalizedString</MaterialLotID>
							<AssemblyType>Other</AssemblyType>
							<AssemblyRelationship>Other</AssemblyRelationship>
						</AssemblySubLotID>
						<AssemblyType>Logical</AssemblyType>
						<AssemblyRelationship>Transient</AssemblyRelationship>
					</MaterialLot>
				</xsl:for-each>
			</DataArea>
		</ProcessMaterialLot>
	</xsl:template>
</xsl:stylesheet>